spring:
  application:
    name: product-service  # 서비스 이름과 Git 파일 이름 일치
  config:
    import: optional:configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: product-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: '*'
